In [1]:
import pandas as pd
import requests

In [2]:
base_url = 'https://data-charts-api.hexlet.app'

visits_url = f'{base_url}/visits?begin=2023-03-01&end=2023-09-01'
registrations_url = f'{base_url}/registrations?begin=2023-03-01&end=2023-09-01'

visits_response = requests.get(visits_url)
registrations_response = requests.get(registrations_url)

In [3]:
visits_response.status_code, registrations_response.status_code

(200, 200)

In [4]:
visits_api = pd.DataFrame(visits_response.json())
registrations_api = pd.DataFrame(registrations_response.json())

In [5]:
visits_api.head()
registrations_api.head()

,datetime,user_id,email,platform,registration_type
0,2023-03-01T07:40:13,2e0f6bb8-b029-4f45-a786-2b53990d37f1,ebyrd@example.org,web,google
1,2023-03-01T13:14:00,f007f97c-9d8b-48b5-af08-119bb8f6d9b6,knightgerald@example.org,web,email
2,2023-03-01T03:05:50,24ff46ae-32b3-4a74-8f27-7cf0b8f32f15,cherylthompson@example.com,web,apple
3,2023-03-01T00:04:47,3e9914e1-5d73-4c23-b25d-b59a3aeb2b60,halldavid@example.org,web,email
4,2023-03-01T18:31:52,27f875fc-f8ce-4aeb-8722-0ecb283d0760,denise86@example.net,web,google

In [6]:
visits_api.info()
registrations_api.info()

<class 'pandas.DataFrame'>
RangeIndex: 263459 entries, 0 to 263458
Data columns (total 4 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   visit_id    263459 non-null  str
 1   platform    263459 non-null  str
 2   user_agent  263459 non-null  str
 3   datetime    263459 non-null  str
dtypes: str(4)
memory usage: 8.0 MB
<class 'pandas.DataFrame'>
RangeIndex: 21836 entries, 0 to 21835
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   datetime           21836 non-null  str
 1   user_id            21836 non-null  str
 2   email              21836 non-null  str
 3   platform           21836 non-null  str
 4   registration_type  21836 non-null  str
dtypes: str(5)
memory usage: 853.1 KB

In [7]:
visits_api.describe(include='all')
registrations_api.describe(include='all')

,datetime,user_id,email,platform,registration_type
count,21836,21836,21836,21836,21836
unique,21821,21836,20868,3,4
top,2023-03-01T09:53:07,2e0f6bb8-b029-4f45-a786-2b53990d37f1,ujones@example.com,android,email
freq,2,1,6,10582,8996